### ISSUE TITLE
Datos de contacto

### ISSUE THREAD

**Issue by lfalvarez** [AntoineBraultChile/siguecovid#1]
Hola!
Primero que nada, me parece bacán cómo te ha quedado el sistema y cuando estaba viendo la página se me ocurrió que quizás podrías agregar un footer con ciertos datos de contacto como este github, o el twitter.
Algo tipo esto quizás https://epicbootstrap.com/snippets/footer-basic.

Saludos y gracias de nuevo.

**Comment by AntoineBraultChile** [comment]
Hola, 
Muchas gracias. Si voy a ver para agregar eso.
Saludos.
