### ISSUE TITLE
Un pequeño error con María Pinto

### ISSUE THREAD

**Issue by lfalvarez** [AntoineBraultChile/siguecovid#2]
Hola!
Tuve un problema viendo los datos de la comuna de `María Pinto` y quizás pase con otras comunas.
Pasos para reproducir:
1) Ir a la sección de comunas y seleccionar `María Pinto` y verificar que los datos no se actualizan. (Esto ocurrió el día 12/07/2021)

Si sirve de algo, la consola muestra el siguiente error:
![imagen](https://user-images.githubusercontent.com/585757/125319604-ea97ea00-e308-11eb-91ea-9ec3d50a328b.png)

Saludos y muchas gracias por este trabajo.

**Comment by AntoineBraultChile** [comment]
Hola,

Gracias por el mensaje.
El error es corregido normalmante.

Saludos.

**Comment by lfalvarez** [comment]
Bacán!
